### ISSUE TITLE
Exclude not working in Style/PredicateName?

### ISSUE THREAD

**Issue by sfroehler** [thoughtbot/hound#1038]
I'm not sure if i'm doing something wrong or if this is a bug:

Im trying to exclude the specs directory from the Style/PredicateName cop, but it still complaints about method names.

I have setup an example PR here: https://github.com/sfroehler/test_project/pull/3

I have setup hound to use the [.ruby-style.yml](https://github.com/sfroehler/test_project/blob/sf-test-predicate-name-settings/.ruby-style.yml) which is a copy of the config you have linked in the hound docs (https://raw.githubusercontent.com/thoughtbot/hound/master/config/style_guides/ruby.yml).

This yml contains the following settings for the Style/PredicateName:

```yml
Style/PredicateName:
  Description: Check the names of predicate methods.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#bool-methods-qmark
  Enabled: true
  NamePrefix:
  - is_
  - has_
  - have_
  NamePrefixBlacklist:
  - is_
  Exclude:
  - spec/**/*
```

If I run rubocop locally with the config it does not complain about the have_* methods in the spec directory but only about the once in app/models.

As you can see here https://github.com/sfroehler/test_project/pull/3#discussion-diff-50282538 hound is still complaining about the method name.

Whats going wrong here?
