### ISSUE TITLE
.jshintignore not working?

### ISSUE THREAD

**Issue by jasonkuhrt** [thoughtbot/hound#1042]
Given this `.hound.yml`:
```
❯ cat .hound.yml
# https://houndci.com/configuration
ruby:
  config_file: .rubocop.yml
scss:
  config_file: .scss-lint.yml
javascript:
  config_file: .jshintrc
  ignore_file: .jshintignore
Given this `.jshintignore`:
```

And this `.jshintignore`:

```
❯ cat .jshintignore
vendor/*
client/**/*.js
client/*
webpack.config.babel.js
```

Why would `HoundCI` continue to lint e.g. `client/components/CardList.js`:

<img width="752" alt="screen shot 2016-01-25 at 2 57 05 pm" src="https://cloud.githubusercontent.com/assets/284476/12562583/0108489e-c374-11e5-8786-212c994e7dcd.png">
