### ISSUE TITLE
Rubocop's `DisabledByDefault: true` doesn't seem to work

### ISSUE THREAD

**Issue by gumatias** [thoughtbot/hound#1049]
Hi! Given the hound config below, for some reason I'm still getting Hound comments in Ruby files, which I was assuming I should not. Am I missing something? 

thanks!

.hound.yml
```
fail_on_violations: false

ruby:
  config_file: .ruby-style.yml
scss:
  enabled: false
javascript:
  enabled: false
coffeescript:
  enabled: false
jscs:
  enabled: false
haml:
  enabled: false
```

.ruby-style.yml
```
AllCops:
  DisabledByDefault: true
```

**Comment by gylaz** [comment]
Which violations are you seeing?

RuboCop states:
```
Note that when DisabledByDefault is true, cops in user
configuration will be enabled even if they don't set the Enabled parameter.
```
Since Hound provides some defaults (that get merged with RuboCop). It might be that RuboCop is enabling the ones from Hounds config. Have a look [here][config] and see if you are getting violations for any of these rules.

[config]:https://github.com/thoughtbot/hound/blob/master/config/style_guides/ruby.yml

**Comment by gumatias** [comment]
thanks for the response @gylaz !

Before I had no styles whatsoever, that was the whole file. So I was assuming Hound would simply ignore all violations. After your comment I went ahead and edited `.ruby-style.yml` to look like this:

```
AllCops:
  DisabledByDefault: true
Metrics/ParameterLists:
  Description: Avoid parameter lists longer than three or four parameters.
  StyleGuide: https://github.com/bbatsov/ruby-style-guide#too-many-params
  Enabled: true
  Max: 5
  CountKeywordArgs: true
```

But unfortunately, Hound still commenting on other violations that are not specified in the file.

I'm making there tests in a simple Ruby project, in case you want to check out: 

[PR with all comments that were not supposed to happen](https://github.com/gumatias/todo_app/pull/19)
[.hound.yml](https://github.com/gumatias/todo_app/blob/master/.hound.yml)
[.ruby-style.yml](https://github.com/gumatias/todo_app/blob/master/.ruby-style.yml)
