### ISSUE TITLE
Hound ignoring path-based excludes with wildcards

### ISSUE THREAD

**Issue by prsimp** [thoughtbot/hound#522]
Given this configuration:

```yml
# ./.hound.yml
ruby:
  enabled: true
  config_file: .rubocop.yml

# ./.rubocop.yml
Style/Blocks:
  Exclude:
    - spec/**/*
```

And a spec file with this sort of syntax:
```ruby
it 'changes something' do
  expect {
    SomeClassName.a_method_that_changes_the_count
  }.to change { SomeClassName.count }
end
```

Locally, Rubocop 0.25.0 does not complain about this block syntax, however, Hound will comment on the line with the `Avoid using {...} for multi-line blocks.` message.

This occurs with other cops (i.e. Style/PredicateName, Style/RescueModifier), but seems to be limited to cops that are using a wildcard pattern (though this is an intuition, not a confirmed fact).

The configuration *is* being detected and loaded, as other rules are respected (particularly when they differ from the default).

Hound is very useful, but it's usefulness is greatly diminished when you're unable to stop it from commenting on non-issues.

Let me know if there's any other info I can add to help diagnose. The repo in question isn't public, but I can create a public dummy project to demonstrate the issue if needed. Thanks in advance!

**Comment by salbertson** [comment]
@prsimp, this has been fixed!

**Comment by prsimp** [comment]
@salbertson thanks for the heads up!

**Comment by djiang** [comment]
Did this fix every get merged in and deployed? I'm trying almost the exact same config as the OP:

```ruby
Style/Blocks:
  Exclude:
    - 'spec/**/*'
```

**Comment by djiang** [comment]
@prsimp @salbertson Are you guys still this issue?

**Comment by djiang** [comment]
Update: It looks like rubocop changed the name to `BlockDelimiters`, so the following now works as expected:

```yml
Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*`
```
