### ISSUE TITLE
Not commenting

### ISSUE THREAD

**Issue by blklane** [thoughtbot/hound#572]
I have hound setup and is currently giving a status in a PR via the Github API but not placing any comments.  Has anyone had a similar problem or have any idea on how to mitigate it?

The `.hound.yml` file looks like:
```yml
java_script:
  enabled: true
ruby:
  enabled: true
  config_file: config/.rubocop.yml
```
