### ISSUE TITLE
Hound ignoring custom rubocop.yml

### ISSUE THREAD

**Issue by bradleypriest** [thoughtbot/hound#683]
Some time in the last couple of weeks Hound has stopped recognizing our custom rubocop config.
We have added SCSS and javascript config as well, but I've rolled it back it just in case that was the issue and it's still an issue.

Here's the config and the account is tied to this Github account, can someone please let me know what's broken?

`hound.yml`
```yml
ruby:
  enabled: true
  config_file: config/.rubocop.yml

coffee_script:
  enabled: true
  config_file: config/.coffeelint.json
```
`config/.rubocop.yml`
```yml
AllCops:
  Exclude:
    - db/schema.rb
    - spec/**/*
ShowCopNames: true

# class Example
# ...
# private
# ...
# end
Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/Blocks:
  Enabled: false

# Allows foo(bar: baz)
Style/BracesAroundHashParameters:
  Enabled: false

Style/DotPosition:
  EnforcedStyle: leading

Style/IndentHash:
  EnforcedStyle: consistent

Style/LineLength:
  Max: 120

Style/RedundantSelf:
  Enabled: false

# We like neatly-aligned code
Style/SingleSpaceBeforeFirstArg:
  Enabled: false

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  Enabled: false

# Allow single or double quotes
Style/StringLiterals:
  Enabled: false
```
