### ISSUE TITLE
Alphabetical SCSS property ordering breaks progressive enhancement

### ISSUE THREAD

**Issue by joaocunha** [thoughtbot/hound#696]
The sorting shouldn't be alphabetical, as it breaks progressive enhancement/graceful degradation practices. Example: 

This (*pseudo(ish)code*):
```css
.fancy {
  background-color: red;
  background-image: url(http://foo.com/radial.png);
  background-position: 80% 20%;
  background-repeat: no-repeat;
  background: -webkit-gradient(radial, 80% 20%, 0, 80% 40%, 100, from(blue), to(cyan));
}
```

Is suggested by the tool to be rewritten as:
```css
.fancy {
  background: -webkit-gradient(radial, 80% 20%, 0, 80% 40%, 100, from(blue), to(cyan));
  background-color: red;
  background-image: url(http://foo.com/radial.png);
  background-position: 80% 20%;
  background-repeat: no-repeat;
}
```

CSSComb is doing a great job on ordering, maybe we could have something similar: https://github.com/csscomb/csscomb.js/blob/master/config/yandex.json
