### ISSUE TITLE
Hound identifies unused variable incorrectly

### ISSUE THREAD

**Issue by halogenandtoast** [thoughtbot/hound#750]
![2015-04-06 9 53 53](https://cloud.githubusercontent.com/assets/201288/7005114/fceabe0e-dc42-11e4-80b5-2d56a2142a7d.png)

**Comment by halogenandtoast** [comment]
.hound.yml
```yaml
scss:                         
  enabled: false
ruby:
  config_file: .ruby-style.yml
```

.ruby-style.yml
```yaml
Style/AlignParameters:
  Enabled: false
```
