### ISSUE TITLE
Ignore SCSS file checks

### ISSUE THREAD

**Issue by JuanitoFatas** [thoughtbot/hound#775]
Is there a counterpart `.scss_ignore` like `.javascript_ignore`:

```yml
scss:
  config_file: .scss-style.yml
  ignore_file: .scss_ignore
```

Thanks!
