### ISSUE TITLE
JavaScript configuration not loading?

### ISSUE THREAD

**Issue by nummi** [thoughtbot/hound#870]
Has anyone else reported Hound not respecting configuration files? We were getting ES6 violations in our PR so we created a `.javascript-style.json`:

```
{
  "esnext": true
}
```

**.hound.yml:**

``` yml
ruby:
  enabled: true
  config_file: .rubocop.yml
coffeescript:
  enabled: true
  config_file: coffeelint.json
javascript:
  enabled: true
  config_file: .javascript-style.json
scss:
  enabled: false
```

We cloned the Hound repo and opened up the rails console. It seems to return back the right options.

``` ruby
gh_key = 'github_api_key'
github = GithubApi.new(gh_key)
full_repo_name = 'owner/repo'
sha = 'latest_commit_sha'
commit = Commit.new(full_repo_name, sha, github)
repo_config = RepoConfig.new(commit)
guide = StyleGuide::JavaScript.new(repo_config, 'owner')
guide.send(:config)
=> {"asi"=>false,
 "bitwise"=>true,
 "browser"=>true,
 "camelcase"=>true,
 "curly"=>true,
 "forin"=>true,
 "immed"=>true,
 "latedef"=>"nofunc",
 "maxlen"=>80,
 "newcap"=>true,
 "noarg"=>true,
 "noempty"=>true,
 "nonew"=>true,
 "predef"=>["$", "jQuery", "jasmine", "beforeEach", "describe", "expect", "it", "angular", "inject", "module"],
 "quotmark"=>true,
 "trailing"=>true,
 "undef"=>true,
 "unused"=>true,
 "esnext"=>true}
```

We also ran jshint locally and used `.javascript-style.json` for the config. It does not show any ES6 errors.

`jshint --config .javascript-style.json ./client/app`
