### ISSUE TITLE
Hound config not respecting config files

### ISSUE THREAD

**Issue by elwayman02** [thoughtbot/hound#879]
Our `.hound.yml` config is as follows:

```
scss:
  enabled: true
  config_file: .scss-lint.yml

javascript:
  enabled: true
  config_file: .jshintrc
```

The `enabled` flags are being respected (ie, if we set them to false, Hound doesn't make any comments), but the `config_file` flags are not. The default Hound rules are being used, even in the case where we have set our own rule to override it.

**Comment by gylaz** [comment]
Can you provide your `.scss-lint.yml` and `.jshintrc` files?

**Comment by monfresh** [comment]
I'm running into this as well. Hound is not respecting the file exclusion that I specified in my `.scss-style.yml`. I tried both of these, and neither worked:
```yaml
linters:
  SelectorFormat:
    exclude:
      - '/assets/stylesheets/custom.scss'
```
```yaml
scss:
  linters:
    SelectorFormat:
      exclude:
        - '/assets/stylesheets/custom.scss'
```

**Comment by elwayman02** [comment]
scss-lint:

```
scss_files: 'app/styles/**/*.scss'
exclude:
- 'app/styles/dazzler/font-icons.scss'
- 'app/styles/dazzler/social-icons.scss'
linters:
  BangFormat:
    enabled: true
  BorderZero: #Don't care
    enabled: false
  ColorKeyword:
    enabled: true
  ColorVariable: #TODO: Fix violations
    enabled: false
  Comment:
    enabled: true
  DebugStatement:
    enabled: true
  DeclarationOrder: #TODO: Fix violations
    enabled: false
  DisableLinterReason:
    enabled: true
  DuplicateProperty:
    enabled: true
  ElsePlacement:
    enabled: true
  EmptyLineBetweenBlocks: #TODO: Determine chosen behavior/Fix violations
    enabled: false
  EmptyRule:
    enabled: true
  ExtendDirective:
    enabled: false
  FinalNewline:
    enabled: true
  HexLength: #Not worth enforcing this rule, though we tend to prefer long
    enabled: false
    style: long
  HexNotation: #Not worth enforcing this rule
    enabled: false
    style: uppercase
  HexValidation:
    enabled: true
  IdSelector:
    enabled: true
  ImportantRule: #TODO: Not sure we can ever turn this one, but we should definitely reduce our use of !important
    enabled: false
  ImportPath:
    enabled: true
  Indentation:
    enabled: true
  LeadingZero: #TODO: Determine chosen behavior/Fix violations
    enabled: false
    style: include_zero
  MergeableSelector: #TODO: Fix violations
    enabled: false
  NameFormat: #None of the default conventions match our style guide
    enabled: false
  NestingDepth: #TODO: Fix violations
    enabled: false
  PlaceholderInExtend: #TODO: Fix violations by adding placeholders
    enabled: false
  PropertyCount:
    enabled: false
  PropertySortOrder: #TODO: Fix violations
    enabled: false
  PropertySpelling:
    enabled: true
  QualifyingElement: #TODO: Fix violations
    enabled: false
  SelectorDepth: #TODO: Fix violations
    enabled: false
  SelectorFormat: #None of the default conventions match our style guide
    enabled: false
  Shorthand:
    enabled: true
  SingleLinePerProperty:
    enabled: true
  SingleLinePerSelector:
    enabled: true
  SpaceAfterComma:
    enabled: true
  SpaceAfterPropertyColon:
    enabled: true
  SpaceAfterPropertyName:
    enabled: true
  SpaceAfterVariableName:
    enabled: true
  SpaceAroundOperator:
    enabled: true
  SpaceBeforeBrace:
    enabled: true
  SpaceBetweenParens:
    enabled: true
  StringQuotes:
    enabled: true
  TrailingSemicolon:
    enabled: true
  TrailingWhitespace:
    enabled: true
  TrailingZero:
    enabled: true
  UnnecessaryMantissa:
    enabled: true
  UnnecessaryParentReference:
    enabled: true
  UrlFormat:
    enabled: true
  UrlQuotes:
    enabled: true
  VariableForProperty:
    enabled: true
  VendorPrefix: #TODO: Fix violations
    enabled: false
  ZeroUnit:
    enabled: true
```

As you can see, we explicitly called out every linter supported, so none of Hound's rules should be used (which was really unexpected in the first place).

Our jshintrc is equally not being used:

```
{
  "predef": [
    "document",
    "window",
    "-Promise",
    "moment",
    "EmberPusher",
    "Pusher",
    "Handlebars",
    "Pikaday",
    "numeral",
    "emoji"
  ],
  "browser": true,
  "boss": true,
  "curly": true,
  "debug": false,
  "devel": true,
  "eqeqeq": true,
  "evil": true,
  "forin": false,
  "immed": false,
  "laxbreak": false,
  "newcap": true,
  "noarg": true,
  "noempty": false,
  "nonew": false,
  "nomen": false,
  "onevar": false,
  "plusplus": false,
  "regexp": false,
  "undef": true,
  "sub": true,
  "strict": false,
  "white": false,
  "eqnull": true,
  "esnext": true,
  "unused": true
}
```

**Comment by elwayman02** [comment]
@gylaz any idea what's going on?

**Comment by elwayman02** [comment]
Bump?

**Comment by gylaz** [comment]
@elwayman02 I tried to reproduce your JavaScript situation here: https://github.com/gylaz/wormbots/pull/14, and Hound seems to be behaving correctly (commenting only on the global that hasn't been configured).

Is there a public PR that you're experiencing this issue with, so I can take a look further. Otherwise, I can take a look at your private PR, and you can contact me via Intercom widget on houndci.com.

**Comment by elwayman02** [comment]
@gylaz it's a private repo, but I've pinged the repo owner to have him reach out via Intercom

**Comment by elwayman02** [comment]
#889 is related; I can't seem to reproduce the other issues we were seeing at this time; we ended up deleting all Hound comments and turning it off in our repo because it was spamming us with too many erroneous messages; now we don't have any examples to show you LOL

**Comment by gylaz** [comment]
If at all possible, maybe one Hound linter can be activated in one particular pull request, then if it makes an erroneous comment you can reach out to us with that example. It's impossible to debug edge-cases without concrete examples :smile:

**Comment by elwayman02** [comment]
Yea, I'm currently working on re-enabling it in our repo, @gylaz, but we are blocked by #889 as it throws multitudes of errors in our repo currently and we cannot compromise by introducing poor linting configs into our project as a workaround.

**Comment by tysongach** [comment]
I’m also having issues with Hound not respecting our scss-lint exclude pattern:

```yaml
scss_files: "app/assets/stylesheets/**/*.scss"
exclude:
  - "app/assets/stylesheets/application_classic/**/*.scss"
  - "app/assets/stylesheets/base/_normalize.scss"
```

Just pushed a branch and Hound made a bunch of comments on `_normalize.scss`, which is _should_ be skipping.

@gylaz Happy to screen-share with you to show you what’s happening or help get to the bottom of this.
