### ISSUE TITLE
"Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping."

### ISSUE THREAD

**Issue by elifoster** [thoughtbot/hound#977]
The comment, "Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping," is generally not true to fit language's style guides. Typically, at least in Ruby, which is what I'm [basing this on](https://github.com/elifoster/SatanicBot/pull/62/files), you use single quotes for strings that do not require variable interpolation, and double quotes for those that do. Perhaps the Hound should check to see if the string is being concatenated rather than simply assuming that single quotes are bad.

**Comment by teoljungberg** [comment]
You can configure hound to use single quotes if you don't want double quoutes.

In your `.hound.yml`:

```yaml
ruby:
  config_file: config/rubocop.yml
```

And in the specified `config_file`:

```yaml
Style/StringLiterals:
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
```

Or, if you want the default rubocop configuration, you can use that https://github.com/bbatsov/rubocop/blob/master/config/default.yml
